### ISSUE TITLE
Missing pieces from old docs (v3 to v7)

### ISSUE THREAD

**Issue by ryyppy** [reason-association/rescript-lang.org#113]
According to #102 there are apparently some missing pieces on features that ppl rely on. 
This thread lists missing items, so we can add them back accordingly.

- `bs.deriving` (jsConverter, abstract)
- Node API docs
- decorator index pointing to the relevant sections

If anyone is missing some other information, please add this to this thread. Some features were initially left out, since there are a lot of features with duplicate functionality.

**Comment by yawaramin** [comment]
It would be great if this issue was linked from https://rescript-lang.org/docs/latest . Otherwise people would not be aware of it.

**Comment by ryyppy** [comment]
#141 adds back documentation for all `@bs.deriving` variants + `@bs.obj`

**Comment by yawaramin** [comment]
I just remembered, also missing docs for modules inherited from OCaml, e.g. `Pervasives`, `List`, `String`, etc. These are important (especially `Pervasives` and in the future `Stdlib`) because they contain docs for basic functionality like `(==)` without which it's difficult to get started. E.g. https://stackoverflow.com/q/65391828/20371

**Comment by ryyppy** [comment]
@yawaramin there's a separate issue for stdlib related content in #120

**Comment by ryyppy** [comment]
i will close this for now, because we have a milestone planned to divide and conquer the problem.
