### ISSUE TITLE
Wrong Pipe Type Used For Promise

### ISSUE THREAD

**Issue by XiNiHa** [reason-association/rescript-lang.org#131]
[(The Documentation)](https://github.com/reason-association/rescript-lang.org/blob/master/pages/docs/manual/latest/promise.mdx)

According to the documentation and the definition, `Js.Promise.then_` receives a callback as the first argument, and the promise to chain as the second argument. However, inside the documentation, `->` is used instead of `|>`, which makes the code invalid.

**Comment by dcalhoun** [comment]
@XiNiHa I believe the `Js.Promise` documentation using `->` (pipe first) was [an intentional change](https://github.com/reason-association/rescript-lang.org/commit/351abc9c5a9ee8c3ed401591aa2653ff06a44d2d) as `|>` (pipe last) [has been "deprecated"](https://rescript-lang.org/docs/manual/latest/pipe#triangle-pipe-deprecated). The `Js.Promise` documentation specifically is leveraging [pipe placeholders](https://rescript-lang.org/docs/manual/latest/pipe#pipe-placeholders) so that `->` is valid code.

I believe `Js.Promise` was created prior to the decision to deprecate the triangle pipe, which is why its argument order may seem odd. Also, it seems like the reality is that pipe-last is largely ["not recommended,"](https://forum.rescript-lang.org/t/rescript-frequently-asked-questions/59/37?u=davidcalhoun) rather than actually deprecated or planned to be removed.

**Comment by XiNiHa** [comment]
Oh, I knew that it was deprecated but thought that it should still be used with current Promise API since the doc mentioned that the new API is coming. Anyway, didn't know about pipe placeholders-sorry for an invalid issue
