### ISSUE TITLE
What does \"@@"(Js.log, Js.Float.toString(param)) mean?

### ISSUE THREAD

**Issue by ruifortes** [reason-association/rescript-lang.org#184]

**Comment by ryyppy** [comment]
`@@` is a custom infix operator. In your example it is used like a regular function.

Right now ReScript doesn't support custom infix operator syntax, that's why you need to escape it with `\"@@"` and then later on use it as a function `\"@@"(arg1, arg2)`.

I assume this is the `@@` operator is coming from the `Pervasives` module, which has following definition:

```
Application operator: g @@ f @@ x is exactly equivalent to g (f (x)).
```

It's not something we'd recommend to use, since you can achieve pretty much the same thing with the way easier to understand pipe syntax: `param->Js.Float.toString->Js.log`
```

**Comment by ruifortes** [comment]
You have put to much faith in my capacity to understand your answer but... I get that it's a monkey path and that I should look into Pervasives ;-)
Thanks

**Comment by ryyppy** [comment]
@ruifortes where did you find this information? if you found that in the language manual, we need to fix it

**Comment by ruifortes** [comment]
yep...in the Belt documentation but just went there and it's fixed now,
Maybe it was a glitch updating the site

**Comment by ruifortes** [comment]
ahh...found it https://rescript-lang.org/docs/manual/latest/api/js/float

**Comment by bdunn313** [comment]
@ryyppy @ruifortes working on a PR that converts the syntax away from this. Just FYI so that we don't double up work. HMU if this is already being worked on.

**Comment by bdunn313** [comment]
@ruifortes see referenced PR for what this potentially should have looked like. I do have an outstanding question of whether or not it is idiomatic to do a normal function call first, then pipe for all subsequent calls, or to pipe from the get-go like in the PR, but either would WORK, and hopefully are less confusing than the examples that prompted your question
